from flask import Flask, render_template

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/message')
def message():
    # Generate dynamic message using Python code
    message_text = "This message is generated by Python!"
    return render_template('message.html', message=message_text)

if __name__ == '__main__':
    app.run(debug=True)
